import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useProjectStore } from '../../store/useProjectStore';
import { adjustPromoPrompt, generateImage } from '../../services/geminiService';
import { ArrowRight, ArrowLeft, Upload, Image as ImageIcon, RefreshCw, CheckCircle2, Loader2, X, Download, AlertCircle } from 'lucide-react';
import { clsx } from 'clsx';
import { downloadAsset } from '../../utils/download';

export default function PromoVisualsStep3() {
  const navigate = useNavigate();
  const { promoScriptData, promoImages, setPromoImage, markStepCompleted, setCurrentStep, updatePromoScenePrompts } = useProjectStore();
  
  const [baseImages, setBaseImages] = useState<string[]>([]);
  const [generating, setGenerating] = useState<Record<string, boolean>>({});
  const [adjusting, setAdjusting] = useState<Record<string, boolean>>({});
  const [confirmed, setConfirmed] = useState<Record<string, boolean>>({});
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const fileInputRef = React.useRef<HTMLInputElement>(null);

  const hasAutoGenerated = React.useRef(false);

  React.useEffect(() => {
    if (promoScriptData && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      promoScriptData.storyboard.forEach(scene => {
        if (!promoImages[scene.scene_number]?.start) {
          generateSceneImage(scene.scene_number, 'start', scene.nano_banana_pro_prompts.start_frame);
        }
      });
    }
  }, [promoScriptData, promoImages]);

  const handleBaseImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files) {
      Array.from(e.target.files).forEach(file => {
        const reader = new FileReader();
        reader.onloadend = () => {
          setBaseImages(prev => [...prev, reader.result as string]);
        };
        reader.readAsDataURL(file);
      });
    }
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  const handleUploadClick = () => {
    fileInputRef.current?.click();
  };

  const removeBaseImage = (index: number) => {
    setBaseImages(prev => prev.filter((_, i) => i !== index));
  };

  const generateSceneImage = async (sceneNumber: number, type: 'start' | 'end', prompt: string) => {
    const key = `${sceneNumber}-${type}`;
    setGenerating(prev => ({ ...prev, [key]: true }));
    
    try {
      const referenceImage = type === 'end' && promoImages[sceneNumber]?.start
        ? promoImages[sceneNumber].start
        : baseImages[0];

      const imageUrl = await generateImage(prompt, '9:16', referenceImage);
      setPromoImage(sceneNumber, type, imageUrl);
      // Unconfirm if regenerating
      setConfirmed(prev => ({ ...prev, [key]: false }));
    } catch (error: any) {
      console.error(`Failed to generate ${type} image for scene ${sceneNumber}:`, error);
      const errorString = error?.message || JSON.stringify(error) || '';
      if (errorString.includes('429') || errorString.includes('RESOURCE_EXHAUSTED')) {
        setErrorMsg('API 配額已用盡，請檢查您的計費方案或稍後再試。');
      } else if (errorString.includes('503') || errorString.includes('UNAVAILABLE')) {
        setErrorMsg('模型目前處於高負載狀態，請稍後再試。');
      } else {
        setErrorMsg(`生成場景 ${sceneNumber} 失敗，請稍後再試。`);
      }
    } finally {
      setGenerating(prev => ({ ...prev, [key]: false }));
    }
  };

  const toggleConfirm = (sceneNumber: number, type: 'start' | 'end') => {
    const key = `${sceneNumber}-${type}`;
    setConfirmed(prev => ({ ...prev, [key]: !prev[key] }));
  };

  const handlePromptAdjust = async (sceneNumber: number, userInput: string, currentPrompts: any) => {
    if (!userInput.trim()) return;
    
    setAdjusting(prev => ({ ...prev, [sceneNumber]: true }));
    try {
      const data = await adjustPromoPrompt(userInput, currentPrompts);
      
      updatePromoScenePrompts(sceneNumber, data);
      // Unconfirm so user can regenerate
      setConfirmed(prev => ({ 
        ...prev, 
        [`${sceneNumber}-start`]: false,
        [`${sceneNumber}-end`]: false 
      }));
    } catch (error: any) {
      console.error('Adjust prompt error:', error);
      setErrorMsg('調整提示詞失敗，請稍後再試。');
    } finally {
      setAdjusting(prev => ({ ...prev, [sceneNumber]: false }));
    }
  };

  const handleNext = () => {
    markStepCompleted(2);
    setCurrentStep(3);
    navigate('/step4a');
  };

  const handleBack = () => {
    navigate('/step2a');
  };

  // Check if all images are generated and confirmed
  const allConfirmed = promoScriptData?.storyboard.every(scene => {
    return confirmed[`${scene.scene_number}-start`] && confirmed[`${scene.scene_number}-end`];
  });

  if (!promoScriptData) {
    return (
      <div className="flex-1 flex items-center justify-center text-neutral-400">
        請先完成步驟 1：產品解構與腳本大綱
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full bg-transparent relative z-10 overflow-hidden">
      <div className="flex items-center justify-between p-4 border-b border-neutral-800/50 bg-neutral-950/60 backdrop-blur-xl shrink-0">
        <div className="flex items-center gap-4">
          <button onClick={handleBack} className="p-2 hover:bg-neutral-800 rounded-full text-neutral-400 transition-colors">
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div>
            <h2 className="text-xl font-semibold text-white tracking-wide">2. 產品視覺注入與首尾影格</h2>
            <p className="text-sm text-orange-400/80 font-mono">PROMO.VISUALS // 生成連貫的產品視覺</p>
          </div>
        </div>
        <button
          onClick={handleNext}
          disabled={!allConfirmed}
          className="flex items-center gap-2 px-6 py-2 bg-orange-600 hover:bg-orange-500 disabled:bg-neutral-800 disabled:text-neutral-500 text-white rounded-lg font-medium transition-colors"
        >
          下一步
          <ArrowRight className="w-4 h-4" />
        </button>
      </div>

      <div className="flex-1 overflow-y-auto p-6">
        <div className="w-full max-w-4xl mx-auto space-y-8">
          
          {errorMsg && (
            <div className="bg-red-900/30 border border-red-500/50 text-red-200 px-4 py-3 rounded-xl flex items-center justify-between">
              <div className="flex items-center gap-2">
                <AlertCircle className="w-5 h-5 text-red-400" />
                <p>{errorMsg}</p>
              </div>
              <button onClick={() => setErrorMsg(null)} className="text-red-400 hover:text-red-300">
                <X className="w-4 h-4" />
              </button>
            </div>
          )}

          {/* Top: Base Images Upload */}
        <div className="bg-neutral-900/40 border border-neutral-800 rounded-2xl p-6">
          <div className="flex items-center gap-2 text-orange-400 mb-4">
            <Upload className="w-5 h-5" />
            <h3 className="font-semibold">實拍圖上傳區</h3>
          </div>
          <p className="text-sm text-neutral-400 mb-4">上傳產品實拍圖作為墊圖，幫助 AI 保持產品外觀的一致性。</p>
          
          <div className="flex flex-wrap gap-4">
            {baseImages.map((img, idx) => (
              <div key={idx} className="relative w-24 h-24 rounded-xl overflow-hidden border border-neutral-700 group">
                <img src={img} alt={`Base ${idx}`} className="w-full h-full object-cover" />
                <button 
                  onClick={() => removeBaseImage(idx)}
                  className="absolute top-1 right-1 bg-black/60 rounded-full p-1 text-white opacity-0 group-hover:opacity-100 transition-opacity"
                >
                  <X className="w-3 h-3" />
                </button>
              </div>
            ))}
            
            <button 
              onClick={handleUploadClick}
              className="w-24 h-24 rounded-xl border-2 border-dashed border-neutral-700 hover:border-orange-500/50 flex flex-col items-center justify-center cursor-pointer transition-colors text-neutral-500 hover:text-orange-400 bg-neutral-950/50"
            >
              <Upload className="w-6 h-6 mb-1" />
              <span className="text-xs">上傳圖片</span>
            </button>
            <input type="file" className="hidden" accept="image/*" multiple ref={fileInputRef} onChange={handleBaseImageUpload} />
          </div>
        </div>

        {/* Bottom: Split Screen Monitor */}
        <div className="space-y-6">
          <div className="flex items-center gap-2 text-orange-400">
            <ImageIcon className="w-5 h-5" />
            <h3 className="font-semibold">分割畫面監視器</h3>
          </div>

          {promoScriptData.storyboard.map((scene) => (
            <div key={scene.scene_number} className="bg-neutral-900/30 border border-neutral-800 rounded-2xl p-6">
              <div className="flex items-center justify-between mb-6">
                <span className="bg-orange-500/20 text-orange-400 px-3 py-1 rounded-md text-sm font-mono font-bold border border-orange-500/30">
                  場景 {scene.scene_number}
                </span>
              </div>

              <div className="flex flex-col md:flex-row gap-8 items-center justify-center">
                {/* Start Frame */}
                <div className="flex-1 w-full max-w-sm space-y-4 flex flex-col items-center">
                  <div className="w-full flex items-center justify-between">
                    <h4 className="text-sm font-medium text-neutral-300">首幀圖</h4>
                    <div className="flex items-center gap-2">
                      <button
                        onClick={() => downloadAsset(promoImages[scene.scene_number].start, `scene_${scene.scene_number}_start.jpg`)}
                        disabled={!promoImages[scene.scene_number]?.start}
                        className="p-1.5 bg-neutral-800 hover:bg-neutral-700 disabled:opacity-50 rounded-md text-neutral-300 transition-colors"
                        title="下載圖片"
                      >
                        <Download className="w-4 h-4" />
                      </button>
                      <button
                        onClick={() => generateSceneImage(scene.scene_number, 'start', scene.nano_banana_pro_prompts.start_frame)}
                        disabled={generating[`${scene.scene_number}-start`] || confirmed[`${scene.scene_number}-start`]}
                        className="p-1.5 bg-neutral-800 hover:bg-neutral-700 disabled:opacity-50 rounded-md text-neutral-300 transition-colors"
                        title="重新生成"
                      >
                        <RefreshCw className={clsx("w-4 h-4", generating[`${scene.scene_number}-start`] && "animate-spin")} />
                      </button>
                      <button
                        onClick={() => toggleConfirm(scene.scene_number, 'start')}
                        disabled={!promoImages[scene.scene_number]?.start}
                        className={clsx(
                          "p-1.5 rounded-md transition-colors flex items-center gap-1 text-xs font-medium",
                          confirmed[`${scene.scene_number}-start`] 
                            ? "bg-emerald-500/20 text-emerald-400 border border-emerald-500/30" 
                            : "bg-neutral-800 hover:bg-neutral-700 text-neutral-400 disabled:opacity-50"
                        )}
                      >
                        <CheckCircle2 className="w-4 h-4" />
                        確定
                      </button>
                    </div>
                  </div>
                  
                  <div className="w-40 bg-neutral-950 rounded-xl border border-neutral-800 overflow-hidden relative flex items-center justify-center" style={{ aspectRatio: '9 / 16' }}>
                    {promoImages[scene.scene_number]?.start ? (
                      <img src={promoImages[scene.scene_number].start} alt="Start Frame" className="w-full h-full object-cover" />
                    ) : generating[`${scene.scene_number}-start`] ? (
                      <div className="flex flex-col items-center gap-2 text-orange-500">
                        <Loader2 className="w-8 h-8 animate-spin" />
                        <span className="text-xs font-mono animate-pulse">生成中...</span>
                      </div>
                    ) : (
                      <div className="text-neutral-600 flex flex-col items-center gap-2">
                        <ImageIcon className="w-8 h-8 opacity-50" />
                        <span className="text-xs">等待生成</span>
                      </div>
                    )}
                  </div>
                  
                  <div className="bg-black/30 p-3 rounded-lg border border-neutral-800/50 w-full space-y-2">
                    <p className="text-xs text-neutral-400 font-mono line-clamp-3 text-center" title={scene.nano_banana_pro_prompts.start_frame}>
                      {scene.nano_banana_pro_prompts.start_frame}
                    </p>
                    {scene.nano_banana_pro_prompts.start_frame_zh && (
                      <p className="text-xs text-neutral-500 font-sans line-clamp-2 text-center border-t border-neutral-800/50 pt-2" title={scene.nano_banana_pro_prompts.start_frame_zh}>
                        {scene.nano_banana_pro_prompts.start_frame_zh}
                      </p>
                    )}
                  </div>
                </div>

                {/* End Frame */}
                <div className="flex-1 w-full max-w-sm space-y-4 flex flex-col items-center">
                  <div className="w-full flex items-center justify-between">
                    <h4 className="text-sm font-medium text-neutral-300">尾幀圖</h4>
                    <div className="flex items-center gap-2">
                      <button
                        onClick={() => downloadAsset(promoImages[scene.scene_number].end, `scene_${scene.scene_number}_end.jpg`)}
                        disabled={!promoImages[scene.scene_number]?.end}
                        className="p-1.5 bg-neutral-800 hover:bg-neutral-700 disabled:opacity-50 rounded-md text-neutral-300 transition-colors"
                        title="下載圖片"
                      >
                        <Download className="w-4 h-4" />
                      </button>
                      <button
                        onClick={() => generateSceneImage(scene.scene_number, 'end', scene.nano_banana_pro_prompts.end_frame)}
                        disabled={generating[`${scene.scene_number}-end`] || confirmed[`${scene.scene_number}-end`] || !confirmed[`${scene.scene_number}-start`]}
                        className="p-1.5 bg-neutral-800 hover:bg-neutral-700 disabled:opacity-50 rounded-md text-neutral-300 transition-colors"
                        title="重新生成"
                      >
                        <RefreshCw className={clsx("w-4 h-4", generating[`${scene.scene_number}-end`] && "animate-spin")} />
                      </button>
                      <button
                        onClick={() => toggleConfirm(scene.scene_number, 'end')}
                        disabled={!promoImages[scene.scene_number]?.end}
                        className={clsx(
                          "p-1.5 rounded-md transition-colors flex items-center gap-1 text-xs font-medium",
                          confirmed[`${scene.scene_number}-end`] 
                            ? "bg-emerald-500/20 text-emerald-400 border border-emerald-500/30" 
                            : "bg-neutral-800 hover:bg-neutral-700 text-neutral-400 disabled:opacity-50"
                        )}
                      >
                        <CheckCircle2 className="w-4 h-4" />
                        確定
                      </button>
                    </div>
                  </div>
                  
                  <div className="w-40 bg-neutral-950 rounded-xl border border-neutral-800 overflow-hidden relative flex items-center justify-center" style={{ aspectRatio: '9 / 16' }}>
                    {promoImages[scene.scene_number]?.end ? (
                      <img src={promoImages[scene.scene_number].end} alt="End Frame" className="w-full h-full object-cover" />
                    ) : generating[`${scene.scene_number}-end`] ? (
                      <div className="flex flex-col items-center gap-2 text-orange-500">
                        <Loader2 className="w-8 h-8 animate-spin" />
                        <span className="text-xs font-mono animate-pulse">生成中...</span>
                      </div>
                    ) : (
                      <div className="text-neutral-600 flex flex-col items-center gap-2">
                        {confirmed[`${scene.scene_number}-start`] ? (
                          <button
                            onClick={() => generateSceneImage(scene.scene_number, 'end', scene.nano_banana_pro_prompts.end_frame)}
                            className="flex flex-col items-center gap-2 text-orange-500 hover:text-orange-400 transition-colors"
                          >
                            <RefreshCw className="w-8 h-8" />
                            <span className="text-xs font-medium">生成尾幀</span>
                          </button>
                        ) : (
                          <>
                            <ImageIcon className="w-8 h-8 opacity-50" />
                            <span className="text-xs text-center px-4">請先確認首幀<br/>再生成尾幀</span>
                          </>
                        )}
                      </div>
                    )}
                  </div>

                  <div className="bg-black/30 p-3 rounded-lg border border-neutral-800/50 w-full space-y-2">
                    <p className="text-xs text-neutral-400 font-mono line-clamp-3 text-center" title={scene.nano_banana_pro_prompts.end_frame}>
                      {scene.nano_banana_pro_prompts.end_frame}
                    </p>
                    {scene.nano_banana_pro_prompts.end_frame_zh && (
                      <p className="text-xs text-neutral-500 font-sans line-clamp-2 text-center border-t border-neutral-800/50 pt-2" title={scene.nano_banana_pro_prompts.end_frame_zh}>
                        {scene.nano_banana_pro_prompts.end_frame_zh}
                      </p>
                    )}
                  </div>
                </div>
              </div>

              <div className="mt-2 bg-neutral-950/50 border border-neutral-800 rounded-lg p-4 space-y-2 w-full max-w-4xl mx-auto relative">
                <input
                  type="text"
                  placeholder={`針對場景 ${scene.scene_number} 進行調整... (按 Enter 送出)`}
                  disabled={adjusting[scene.scene_number]}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') {
                      handlePromptAdjust(scene.scene_number, e.currentTarget.value, scene.nano_banana_pro_prompts);
                      e.currentTarget.value = '';
                    }
                  }}
                  className="w-full bg-neutral-900 border border-neutral-800 rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-orange-500/50 disabled:opacity-50"
                />
                {adjusting[scene.scene_number] && (
                  <div className="absolute right-6 top-1/2 -translate-y-1/2">
                    <Loader2 className="w-4 h-4 text-orange-500 animate-spin" />
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
        </div>
      </div>
    </div>
  );
}
